twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        default_locale: '%app.default_locale%'
        locales: '%app.locales%'
        timezone: '%app.timezone%'
        mailer_from: '%app.mailer.from%'
        mailer_name: '%app.mailer.name%'
        public: '%app.path.public%'
        org : {'name': '%app.about.name%', 'abbr':'%app.about.abbr%', 'url':'%app.about.url%'}
        path : {'imageEntire': '%app.path.associates.entire%',
                'thumbEntire': '%app.path.associates.entire%/thumbs',
                'imagePortrait': '%app.path.associates.portrait%',
                'thumbPortrait': '%app.path.associates.portrait%/thumbs',
                'documents': '%app.path.documents%'}
        manager: '@App\Service\ProfileManager'
    form_themes:
         - 'bootstrap_5_layout.html.twig'
    paths:
        '%kernel.project_dir%/assets/css': styles

when@test:
    twig:
        strict_variables: true
