vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        associates:
            uri_prefix: /images/associates
            upload_destination: '%kernel.project_dir%/asssets/images/associates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
